### ISSUE TITLE
substitute RasPi for MacOS? (plus other questions)

### ISSUE THREAD

**Issue by JangoBritt** [platta/baby-connect-alexa-skill#1]
Hey Platta!

Got to say that this looks awesome, and I've been hoping I'd find something like this along the way... I'm sure the wife will love it as much as I do... (and therefore approve the purchase of additional Echo devices. lol)

Is there any chance that the RasPi Listener could be adapted to run in Node.JS on MacOS?

I see the AWS SQS is free up to 1 million requests per month... I guess this skill alone wouldn't come close to using that per month... I guess one message on queue per Alexa command?

What is the syntax to use for the skill? is it just everything in the SampleUtterances.txt?

You're probably too far into your baby's development now, for it to matter particularly to you Have you considered adding commands for sleep? starting/stopping, etc?

**Comment by platta** [comment]
Whether you're still expecting or have already given birth, congratulations to you and your wife!

The listener should run on OS X without any changes. Not 100% sure about the nightmare library that handles the browser automation, but I don't see anything in their documentation stating otherwise.

Note that the SQS request limit for free tier applies to:
- Requests to add items to the queue.
- Requests to delete items from the queue once they have been processed.
- Requests to get items from the queue.

That last one has the most impact since the listener polls the queue every 20 seconds (131,400 requests per month). This is the longest polling window AWS allows.

As for using the skill, I would say something like "Alexa, tell Baby Connect that <Child> had 4 ounces of formula." So you can basically say "Alexa, tell Baby Connect," followed by anything from the utterances file.

I've thought about adding more capabilities to round out the feature set, but I dismantled my setup to give to a friend when they had a baby, so it's pretty low on my priority list!

Let me know if you run into any issues. I tried to document everything but I may have missed a detail here or there.

**Comment by platta** [comment]
Oh, I also forgot to mention - if you're running the listener in OS X that probably means you're not running it as a headless server, so you can probably skip all the stuff involving Xvfb and setting the DISPLAY environment variable when invoking the listener.

**Comment by JangoBritt** [comment]
I have absolutely no idea what that means. This may not be as easy as I want hoping. Lol

**Comment by platta** [comment]
No worries! It's explained better in the readme for [baby-connect-sqs-listener](https://github.com/platta/baby-connect-sqs-listener).

Basically, the code interacts with BabyConnect by running a hidden web browser session. It still needs a GUI environment for that, even though it's hidden. Xvfb is short for X Virtual FrameBuffer, and it's a package used to kind of fake out the GUI part for running on a server that's not actually running some kind of windows environment. All I was saying is If you're on OS X you shouldn't need that part.

**Comment by JangoBritt** [comment]
Thanks. Going to give it a try today. Since it's pretty quiet around here, I won't bother to open separate issues for each question, as they're not really "issues"... I'll just keep my questions in this thread, if that's alright, unless you want to connect via Facebook or something?

Firstly, at the moment, I'm just manually copy & pasting the SpeechAssets into the Amazon Dev Console portal... Is there any other way to do that directly from github?

Also, from what I understand of AWS, it's basically CAAS, right? so why do you need the separate listener service running locally, and not on an AWS instance?

I've got to say I've never done anything with AWS or Lambda before, so I've no clue what I'm doing. Sorry for being such a noob. lol

I appreciate your help with all this, I'm sure you've got better things to do.

**Comment by JangoBritt** [comment]
Scratch that first question, I'm a little further along.

I've signed up to AWS, and an Amazon Dev acount.

I've set up Lambda, and an SQS queue (called baby-connect).

I downloaded the repo, and installed npm into the src folder, then uploaded src.zip to a Function in AWS Lambda called baby-connect-alexa-skill.

When I hit Test I get the error:

```
2017-01-04T15:49:57.033Z	708408be-d295-11e6-96f3-65b66a0c8722	TypeError: Cannot read property 'locale' of undefined
    at AlexaRequestEmitter.HandleLambdaEvent (/var/task/node_modules/alexa-sdk/lib/alexa.js:102:38)
    at AlexaRequestEmitter.Object.defineProperty.value (/var/task/node_modules/alexa-sdk/lib/alexa.js:91:31)
    at exports.handler (/var/task/index.js:17:11)
END RequestId: 708408be-d295-11e6-96f3-65b66a0c8722
REPORT RequestId: 708408be-d295-11e6-96f3-65b66a0c8722	Duration: 139.95 ms	Billed Duration: 200 ms 	Memory Size: 128 MB	Max Memory Used: 29 MB	
RequestId: 708408be-d295-11e6-96f3-65b66a0c8722 Process exited before completing request

```

Could that be a permissions issue? what permissions do i need to configure for my Lambda Role?

In the meantime, I also started an Alexa Skill in the Dev console called Baby Connect, and connected it up to the Lambda Function. So far, when simulating the utterance "Olivia drank 180 ml of milk" I still get "The remote endpoint could not be called" I figure that's because the Function isn't testing out properly.

**Comment by JangoBritt** [comment]
I've also just noticed that npm install didn't install the "aws-sdk" module in /node_modules despite it being listed as required in the index.js

const AWS = require('aws-sdk');
const Alexa = require('alexa-sdk');
const nconf = require('nconf');

**Comment by platta** [comment]
The reason I built the listener to run on a Raspberry Pi is for cost savings. Having an EC2 instance running 24/7 just to pick up queue messages would be more expensive than it's worth.

The reason aws-sdk doesn't get installed when you execute `npm install` is because it's not listed in package.json. The node environment in a Lambda function will always have the latest version of aws-sdk available globally, so it's not needed.

Check out the CloudFormation template in the baby-connect-sqs-listener repository. In the AWS Management Console, there is a CloudFormation Template Designer you can use to open it so you're not just reading the raw JSON. The template defines two managed policies that will show you the permissions you'll need.

The error you get when testing the Lambda function directly doesn't look familiar to me. It's probably related to the test input you're providing to the Lambda function. It's usually best to test using the simulated utterances, because that will always send the correct input to Lambda. You can add console.log() commands to the Lambda function to give yourself debug information, and they will be captured in the CloudWatch logs. You can view those by going to the Monitoring tab in the Lambda function and clicking "View logs in CloudWatch".

The error you're getting with your sample utterances could be a permissions issue beyond the policies I mentioned above. When you create the Lambda function you have to specify the Alexa Skills Kit as a trigger. That sets up kind of a trust between your function and the Alexa Skills Kit so that it's "allowed" to invoke your function. That could be the issue you're hitting, too.

For someone just getting started with AWS, you're making fine progress. It is a huge body of knowledge to tackle. I think it's great to have this thread available for others to see, as well. Keep working at it, and don't hesitate to run through some of the Alexa Skills Kit examples if you're still having issues. They're quick and straightforward.

**Comment by JangoBritt** [comment]
ok, I'm not totally clear on what you were suggesting I do with the CloudFormation Template... I see the  two branches leading into the BabyConnect SQS Queue, but what am I doing with this next? or is it just to see the permissions required for the Function's Role permissions? (actually that answer is still unclear from the graphical representation. lol)

Interestingly, I saw in the CLoudWatch logs that the process was timing out at 3 secs, so I increased the timeout to 10. When I simulate "Olivia had a wet diaper" I get:
```

{
  "version": "1.0",
  "response": {
    "outputSpeech": {
      "type": "SSML",
      "ssml": "<speak> Sorry, something went wrong. </speak>"
    },
    "shouldEndSession": true
  },
  "sessionAttributes": {}
}
```

**Comment by platta** [comment]
Oh, sorry. In the template designer, if you select one of the managed policy items, it should pull up the JSON for it on the bottom. That JSON will contain the policy document that defines the permissions the policy grants. That's all I wanted you to see there.

That "something went wrong" message is the default return value you'll get if something doesn't work. There may still be more data in the CloudWatch logs now that you're not timing out. At this point it might be because your Lambda function doesn't have permissions to write to the SQS Queue.

Quick overview of the way the permissions stuff works:
- Permissions are defined by Policies.
- Policies get attached to Users, Groups, or Roles.
- Users and Groups are self-explanatory, but Roles get used by other resources like a Lambda function or an EC2 instance. This allows you to apply permissions _directly_ to your AWS resources.
- Policies can be defined separately (managed policies) and attached to other entities or defined inline on the entity (inline policies).
- All of this stuff is defined in the IAM console.

So what you'll probably want to do is check out the role that your Lambda function is using in the Lambda console. AWS probably created one automatically that gives it permissions to write to the CloudWatch logs. You will want to modify that role (in the IAM console) and add a new Policy (whether you create a managed policy and attach it or define an inline policy directly on the role). Either way, the contents of that policy will be a JSON document whose format you can see by looking at existing policies and also in the CloudFormation template.

One last thing about the CloudFormation template - in the policy documents defined there, you're going to see something like this:

```JSON
"Resource": {
    "Fn::GetAtt": [
        "BabyConnectSQSQueue",
        "Arn"
    ]
}
```
Part of that is CloudFormation specific, because it's referencing another resource that is defined in the template (BabyConnectSQSQueue) and retrieving (Fn::GetAtt) an attribute (Arn) from it. If you're manually creating the policy you can do it one of two ways:

The easy way:
```JSON
"Resource": "*"
```
Which grants permissions to __all__ SQS queues.

The more secure way:
```JSON
"Resource": "arn:aws:sqs:region-name:account-id:queue-name"
```
Where you'd replace this dummy ARN (Amazon Resource Name) with the actual ARN of your SQS queue. This is a better solution because it's more secure, but requires the extra step of looking up the ARN for your queue.

Sorry if I'm throwing a lot of information at you. I've been studying for AWS certification exams recently so my brain just leaks information.

**Comment by JangoBritt** [comment]
OK... I'll pretend I understood all that. lol

I did already add the SQS Queue permission, so it's not that.

The log file actually says:
Warning: Application ID is not set
and
Missing required key 'QueueUrl' in params

I think those are defined in the config.default.json file (as sqsQueueUrl and alexaAppId)... which I haven't uploaded anywhere, (it wasn't mentioned in the readme.md) as it's not part of the SRC folder zip file. Where does that go?

The SQS Queue name is already defined in the DLQ Resource section of the Function, so this must be something required in the actual node.JS file.

**Comment by platta** [comment]
Aha, the `config.default.json` file is a template for you to use to create a `config.json` file, which should go in the `src` folder and get zipped into your zip file along with everything else. I should add that to the readme.

**Comment by JangoBritt** [comment]
woot! that fixed it.
"OK."

I now have one Message in the queue. Now comes the difficult part, getting it out of the queue and in to Baby Connect. lol :-/

**Comment by JangoBritt** [comment]
OMG! it works!

**Comment by platta** [comment]
Awesome! As long as the listener is running it will continuously pick up items and process them. SQS also hangs onto unprocessed items for a few days (I think 3 or 4 by default), so if you have any issues the listener will still get to all the outstanding items when you restart it.

**Comment by JangoBritt** [comment]
this is pretty cool!

Although I find it strange that the Web app logs a dirty nappy as "BM" whereas the iOS app logs it as "Poopy". I guess the baby-connect module in the listener only uses the checkboxes, rather than changing the actual text of the entry?

I also added a few utterances to allow "Nappy" instead of "Diaper" (silly yanks! :p)

**Comment by JangoBritt** [comment]
To outline my experience from start to finish, I don't know if you want to add any of this to the Readme.MD for noobs like me...


Sign up for a free AWS account (aws.amazon.com)
Create a new SQS Message queue
 - Default Options 
Get Started with AWS Lambda, and add a Function
 - Blank Function
 - Add Alexa Skills Kit as a Trigger
 - Populate config.json inside the SRC folder with Queue URL and AppID
 - Upload via ZIP as per Readme.MD
 - Create a Role that includes Basic Execution, and SQS Full Access
 - Set timeout to 10 seconds (maybe increasing Memory would reduce the processing time?)
 - Set DLQ Resource to SQS, and Select the ARN of the Queue
 - Testing from Lambda doesn't produce any results, because there's no configured input.

Sign up for free Developer account (developer.amazon.com)
 - Create new Alexa Skill
 - Manually add Slot Types _before_ trying to paste in Sample Utterances
 - I found I had to test Alexa's voice recognition here... she recorded "poopy", and not "poopie" as per your US implementation, so I changed that (and in the listener's index.js too)
 - Added localised language variants (Nappy vs. Diaper) for Sample utterances
 - copied ARN from Lambda function.

Listener for MacOS
 - installed as per readme.MD
 - Create a User in AWS > IAM with SQSFullAccess permissions 
 - Populate config.json using AccessKeyID and SecretAccessKey from above user
 - run from Terminal

Some things to note... Apparently, my daughter is called Bolivia, maybe I need to annunciate better. EDIT - no matter how I pronounce it, Alexa just doesn't get "Olivia" lol. Maybe this skill needs some Defaults, and shortcuts "Tell baby connect 120 ml" would go for the default baby, and milk"


"mil" "Millilitres" "Em-El"


I'm tempted to investigate whether the listener could be installed on a t1.micro EC2 instance... at the spot prices, it would work out to USD$27 / year, but I don't know why, when I have a perfectly good mac at home... need to investigate the Daemon more.

**Comment by platta** [comment]
This is a lot of great feedback. I do want to incorporate all of it and organize the repositories better, it's just probably going to take me some time to get to it. No idle moments when there's a baby around the house!

I like the idea of setting up utterances where you don't have to specify a name. I'll have to look into that too.

I've actually been working on a solution that's completely in the cloud. It uses an auto-scaling group so that you don't have an EC2 instance sitting around all the time if you're not actively putting items in the SQS Queue. Hopefully I'll be able to publish that soon.

Could you post what you wound up using for your utterances text? I'll create two separate files for en-US and en-GB so they're both fully available.

**Comment by JangoBritt** [comment]
Well.. wouldn't you know it... I asked Baby Connect on their Facebook page whether they were considering IFTTT or Alexa, and they replied that they were actually working on a small API to be released in the next few weeks!

https://www.facebook.com/babyconnect/posts_to_page/

I know that screws over all the great work you've done with the skill, but it might make integration for more functions easier

**Comment by platta** [comment]
Whoa! That's awesome!

Yes, it does make all the work I've done obsolete, but with a proper REST API the entire thing can be run from within Lambda without having to use SQS or a listener application. That's huge!

Thanks for letting me know.

**Comment by polohero** [comment]
You could save yourself some time and use Baby Stats (www.babystats.org) for the Alexa part. There is a public API, as well as IFTTT integration.

**Comment by platta** [comment]
I was unaware of this project. Looks like a great resource!
